ListWizard/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace ListWizard.Controllers
{
    public class AuthController : Controller
    {
        private readonly AuthService _authService;
        private readonly UserManager<User> _userManager;

        public AuthController(AuthService authService, UserManager<User> _userManager)
        {
            this._authService = authService;
            this._userManager = _userManager;
        }
        public ViewResult Index()
        {
            return View();
        }
                                                            
        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login login)
        {


            string authResult = await _authService.LoginUserAsync(login);
            if (authResult == "Success")
            {
                return RedirectToAction("CreateNewList","Wizard");
            }
            else
            {
                ViewBag.message = authResult;
                return View(login);
            }
        }

        public ViewResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(Register register)
        {
            if (ModelState.IsValid)
            {
                var result = await _authService.RegisterUserAsync(register);
                if (result.Succeeded)
                {
                    return RedirectToAction("Login");
                }

            }
            return View(register);
        }

        public ViewResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordViewModel forgotPassword)
        {
            if (ModelState.IsValid)
            {
                var sendEmail = await _authService.ForgotPasswordAsync(forgotPassword.Email);
                    //var validUser = await _userManager.FindByEmailAsync(forgotPassword.Email);
                    //var token = await _userManager.GeneratePasswordResetTokenAsync(validUser);
                    //var passwordresetLink = Url.Action("ResetPassword", "Auth", new { email = forgotPassword.Email, token = token }, Request.Scheme);
                    return RedirectToAction("ResetPassword");

            }
            else
            { return View();}
        }

        public IActionResult ResetPassword()
        {
            return View();
        }

        public IActionResult ResetPassword(ResetPasswordViewModel resetPassword)
        {
            return View();
        }
    }
}

ListWizard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListWizard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListWizard.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.css" />

  </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ListWizard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wizard" asp-action="CreateNewList">New list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wizard" asp-action="Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <div class="modal" tabindex="-1" id="form-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
      </div>
      @*<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>*@
    </div>
  </div>
</div>




    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ListWizard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="datatables/js/jquery.dataTables.js"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>