ListWizard/Controllers/WizardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ListWizard.Controllers
{
    public class WizardController : Controller
    {
    
        private readonly ListWizardContext context;
        private readonly FileService fileService;
        public WizardController(ListWizardContext context, FileService fileService)
        {
            this.context = context;
            this.fileService = fileService;
        }
        public async Task<IActionResult> Index()
        {
            var contents = await context.WizardLists.Where(l=>l.IsDeleted == 0).ToListAsync();
            return View(contents);
        }

        public ViewResult CreateNewList()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateNewList(WizardList wizardList)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetObject("newListInfo", wizardList);
                return RedirectToAction("FileUpload");
            }
 
            return View(wizardList);
        }

        public IActionResult FileUpload()
        {
            Upload upload = new Upload();
            return View(upload);
        }

        [HttpPost]
        public IActionResult FileUpload(Upload uploadedFile)
        {
            if (ModelState.IsValid)
            {
                var result = fileService.FileUploadAsync(uploadedFile).Result;
                return View(result);
            }
            return View(uploadedFile);
        }

        public IActionResult CreateNewListPartial()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult CreateNewListPartial(WizardList wizardList )
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetObject("newListInfo", wizardList);
                return Ok();
            }
            return View();
        }

        public PartialViewResult FileUploadPartial()
        {
            Upload upload = new Upload();
            return PartialView(upload);
        }


        [HttpPost]
        public IActionResult FileUploadPartial(IFormFile uploadedFile)
        {

            //var files = HttpContext.Request.Form.Files.GetFile("uploadedFile");

            if (ModelState.IsValid)
            {
                //var result = fileService.FileUploadAsync(uploadedFile).Result;
                //return View(result);
            }
            return View(uploadedFile);
        }
    }
}
                            
                            
    
    
    
                    
                    
    
    
    
    
    
    
                        

ListWizard/Views/Wizard/CreateNewList.cshtml
@model ListWizard.Models.WizardList

@{
    ViewData["Title"] = "CreateNewList";
    //Layout = null;
}

<h1>CreateNewList</h1>

<h4>WizardList</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewList">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ListName" class="control-label"></label>
                <input asp-for="ListName" id="listName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit"   value="Next" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ListWizard/Views/Wizard/CreateNewListPartial.cshtml
@model ListWizard.Models.WizardList

<h4>WizardList</h4>

<div class="modal" tabindex="-1" id="form-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <form asp-action="CreateNewListPartial" id ="form_data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ListName" class="control-label"></label>
                <input asp-for="ListName" id="listname" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignedTo" class="control-label"></label>
                <input asp-for="AssignedTo" id="assignedto" class="form-control" />
                <span asp-validation-for="AssignedTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" id="createdate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="button" onclick='submitFormData()'  @*onclick="showInPopup('@Url.Action("FileUploadPartial","Wizard",null,Context.Request.Scheme)','Upload')"*@ class="btn btn-success button2" value="Next" />
            </div>
        </form>



<div>
    <a asp-action="Index">Back to List</a>
</div>
      </div>
    </div>
  </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

   

}

ListWizard/Views/Wizard/FileUpload.cshtml
@model ListWizard.Models.Upload
@{
    ViewData["Title"] = "FileUpload";
    //Layout = null;
}

<h1>FileUpload</h1>


<form enctype="multipart/form-data" method="post" >
    <dl>
        <dt>
            <label asp-for="@Model.File"></label>
        </dt>
        <dd>
            <input asp-for="@Model.File" type="file">
            <span asp-validation-for="@Model.File"></span>
        </dd>
         <div class="container">
         
     </div>
    </dl>
    <div class="form-group">
                <input type="submit" value="Finish" class="btn btn-primary" />
            </div>

    
</form>
<p>
    <a asp-action="CreateNewList" asp-controller="Wizard"  class="btn btn-success button2">Back to list</a>
</p>
 @if (Model.csvContents.Count() > 0)
    {
        <h1>Missing fields are @Model.MissingField</h1>
        <h1>Imported fields are @Model.ImportedField</h1>
        <table >
            <tbody>
                @foreach (var cell in Model.csvContents)
                {
                    <tr>
                        <td>
                            @cell.FirstName
                        </td>
                        <td>
                            @cell.LastName
                        </td>
                        <td>
                            @cell.CompanyName
                        </td>
                        <td>
                            @cell.Title
                        </td>
                        <td>
                            @cell.Email
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
  <script src="~/lib/jquery/dist/jquery.js"></script>
      <script src="~/lib/datatables/js/jquery.dataTables.js"></script>

ListWizard/Views/Wizard/FileUploadPartial.cshtml
@model ListWizard.Models.Upload
@{
    ViewData["Title"] = "FileUploadPartial";
    Layout = null;
}

<div id="fileUpload"></div>

   <div class="modal" tabindex="-1" id="form-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
<form enctype="multipart/form-data" id="uploadpart" method="post" >
    <dl>
        <dt>
            <label asp-for="@Model.File"></label>
        </dt>
        <dd>
            <input asp-for="@Model.File"  id="uploadfile" type="file">
            <span asp-validation-for="@Model.File"></span>
        </dd>
         <div class="container">
         
     </div>
    </dl>
    <div class="form-group">
                <input type="button" onclick="onUploadSubmit()"  value="Finish" class="btn btn-primary" />
            </div>

    
</form>
<p>
    <a @*asp-action="CreateNewList" asp-controller="Wizard"*@  onclick="showInPopup('@Url.Action("CreateNewList","Wizard",null,Context.Request.Scheme)','New List Wizard')" class="btn btn-success button2">Back to list</a>
</p>
 @if (Model.csvContents.Count() > 0)
    {
        <h1>Missing fields are @Model.MissingField</h1>
        <h1>Imported fields are @Model.ImportedField</h1>
        <table >
            <tbody>
                @foreach (var cell in Model.csvContents)
                {
                    <tr>
                        <td>
                            @cell.FirstName
                        </td>
                        <td>
                            @cell.LastName
                        </td>
                        <td>
                            @cell.CompanyName
                        </td>
                        <td>
                            @cell.Title
                        </td>
                        <td>
                            @cell.Email
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
      </div>
    </div>
  </div>
</div>

ListWizard/Views/Wizard/Index.cshtml
    @model IEnumerable<ListWizard.Models.WizardList>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div id="placeHolder"></div>
@*<p>
    <a asp-action="CreateNewList" asp-controller="Wizard" class="btn btn-success button2">Create new List</a>
</p>*@
<p>
    <a  class="btn btn-success button2" onclick="showInPopup('@Url.Action("CreateNewListPartial","Wizard",null,Context.Request.Scheme)','New List Wizard')" >Create new List</a>
</p>
<p>
    <button type="submit" asp-action="Delete" >Delete</button>
</p>
<table class="table" id="gridView">
    <thead>
        <tr>
            <th>

            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.ListName)*@ListName
            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.AssignedTo)*@Assigned to
            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.CreatedDate)*@Created Date
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.ModifiedDate)*@Modified Date
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <input type="checkbox" asp-route-id = "@item.ListId"/>
                @*<a asp-action="Edit"  asp-route-id="@item.ListId">Edit</a> *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ListName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>

            
        </tr>
}
    </tbody>
</table>
@*   <script src="~/lib/jquery/dist/jquery.js"></script>
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>  
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />  
  
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />  
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />  
  
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>  
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>  
@section Scripts{
    <script>
    
    $(document).ready(function(){

        $('#gridView').DataTable();
        
    });
    
    </script>

}*@

ListWizard/Views/Wizard/Temp.cshtml
    @model IEnumerable<ListWizard.Models.WizardList>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div id="placeHolder"></div>
<p>
    <a @*asp-action="CreateNewListPartial" asp-controller="Wizard" > Create New *@ class="btn btn-success button2" onclick="showInPopup('@Url.Action("CreateNewListPartial","Wizard",null,Context.Request.Scheme)','New List Wizard')" >Create new List</a>
</p>
<p>
    <button type="submit" asp-action="Delete" >Delete</button>
</p>
<table class="table" id="gridView">
    <thead>
        <tr>
            <th>

            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.ListName)*@ListName
            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.AssignedTo)*@Assigned to
            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.CreatedDate)*@Created Date
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.ModifiedDate)*@Modified Date
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <input type="checkbox" asp-route-id = "@item.ListId"/>
                @*<a asp-action="Edit"  asp-route-id="@item.ListId">Edit</a> *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ListName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>

            
        </tr>
}
    </tbody>
</table>
@*   <script src="~/lib/jquery/dist/jquery.js"></script>
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>  
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />  
  
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />  
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />  
  
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>  
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>  
@section Scripts{
    <script>
    
    $(document).ready(function(){

        $('#gridView').DataTable();
        
    });
    
    </script>

}*@